## Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [4]:
mean_a = a.mean(axis=0)

In [5]:
mean_a

array([2. , 8.4])

## Задание 2

In [14]:
a_centered = np.array([a[i] - mean_a for i in range(5)])

In [15]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [16]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1] # чтобы получить столбцы, можно взять строки от транспонированной матрицы

In [17]:
a_centered_sp / 4  # делим на N-1 наблюдений, в нашем случае их 5, значит N-1 = 4

2.0

## Задание 4

In [14]:
a_cov = np.cov(a.T)

In [15]:
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [16]:
a_cov[0][1] # искомое значение ковариации с индексами [0][1] в данной матрице. Как видим значение равно значению из 3 задания

2.0