In [9]:
import numpy as np

### Задание 1

In [6]:
a = np.arange(12, 24)

In [7]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [9]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 3

In [15]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 4

In [25]:
np.ndim(a)

1

In [27]:
np.ndim(a.reshape(-1, 1))

2

как видим если переделать из одномерного массива строку в столбец, и проверить методом ndim мы получаем размерность 2. Это означает что массив из 1 столбца и 12 строк - двумерный. Наличие более 1 строчки подразумевает что массив - двумерный, даже если в каждой строчке только 1 значение.

### Задание 5

In [61]:
b = np.random.randn(3, 4)
b

array([[-0.39811867, -0.57593806,  0.36715587, -0.54533552],
       [-1.25554579,  0.17244572, -1.44316615, -0.51051091],
       [ 0.54469974, -1.38184972,  0.29318908, -0.88432567]])

In [62]:
b.size

12

In [63]:
b.flatten()

array([-0.39811867, -0.57593806,  0.36715587, -0.54533552, -1.25554579,
        0.17244572, -1.44316615, -0.51051091,  0.54469974, -1.38184972,
        0.29318908, -0.88432567])

In [64]:
b.flatten().size

12

In [65]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [54]:
b = np.arange(20, 1, -2)

In [55]:
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

в итоговых результатах разницы нет, суть в том что 1 не попадает в шаг -2. В свзяи с этим массивы одинаковые, если бы был шаг -1,
то в массиве "a" еще бы было дополнительно значение 1.

### Задание 8

In [70]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [71]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
np.vstack((a, b))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Задание 9

In [115]:
c = np.arange(0, 12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
A = c.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [120]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [121]:
b = A @ At
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [122]:
np.linalg.det(A @ At)

0.0

Размер итоговой матрицы 4*4.(строк как у первой, столбцов как у второй) Обратную матрицу посчитать нельзя так как определитель равен 0

### Задание 10

In [124]:
import random

In [125]:
random.seed(42)

### Задание 11

In [126]:
m = np.random.randint(0, 16, 16)
m

array([15,  0,  4,  0,  6, 13,  2,  6,  9, 13, 14, 11,  5,  0,  7,  4])

### Задание 12

In [136]:
c = m.reshape(4,4)
c

array([[15,  0,  4,  0],
       [ 6, 13,  2,  6],
       [ 9, 13, 14, 11],
       [ 5,  0,  7,  4]])

In [137]:
d = b + c * 10
d

array([[155,  14,  63,  32],
       [ 74, 180, 106, 182],
       [113, 216, 289, 322],
       [ 82, 122, 282, 342]])

In [138]:
np.linalg.det(d) #определитель


345624399.9999995

In [139]:
np.linalg.matrix_rank(d)

4

In [140]:
d_inv = np.linalg.inv(d)
d_inv

array([[ 7.08520579e-03,  3.60402796e-03, -4.28193148e-03,
         1.45064990e-03],
       [-2.26673811e-03,  2.12774330e-03,  7.52470022e-03,
        -8.00487466e-03],
       [-1.03748462e-03, -1.46520905e-02,  1.66984160e-02,
        -7.82751449e-03],
       [-3.47197709e-05,  1.04584051e-02, -1.54264572e-02,
         1.18859664e-02]])

### Задание 13

In [181]:
d_inv[d_inv > 0] = 1

In [182]:
d_inv[d_inv < 0] = 0

In [183]:
d_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [184]:
ind1 = np.where(d_inv == 1)

In [185]:
ind0 = np.where(d_inv == 0)

In [186]:
e[ind0] = c[ind0]

In [187]:
e[ind1] = b[ind1]

In [190]:
e

array([[  5.,  14.,   4.,  32.],
       [  6.,  50.,  86.,   6.],
       [  9.,  13., 149.,  11.],
       [  5., 122.,   7., 302.]])